### ISSUE TITLE
Icons don't appear after adding FontAwesome to FontBook

### ISSUE THREAD

**Issue by winmillwill** [koekeishiya/Statusbar#1]
I wonder if you may have pasted into your .coffee plugins from an older version of the .otf than I can find. Today if you go to fontawesome.com you get an archive with several .otf files, and after adding them to Font Book, I still see empty squares where the symbols should be. Is there some trick to setting the font of uebersicht, or setting the font of my editor to include font awesome symbols in addition to its current font?

**Comment by koekeishiya** [comment]
No idea. I've added the FontAwesome.otf that I use in the repo. No changes should be necessary when using that.

**Comment by winmillwill** [comment]
Cool, thanks for adding the file, I see icons now.
