### ISSUE TITLE
question about spotify location

### ISSUE THREAD

**Issue by ChrisCallanJr** [koekeishiya/Statusbar#6]
looking at the spotify.sh script, it is pointing to `usr/local/bin/spotify` but I looked and spotify doesn't exist there, even though I have spotify installed. should I be pointing the script somewhere else? I am on High Sierra if that matters. Thanks!

**Comment by koekeishiya** [comment]
You probably resolved this as the issue is closed, but it is mentioned how the spotify.sh script works in the README.md of the repository. It basically uses a third-party script that controls the Spotify application using applescript.
